# _config.yml

title: Habiter
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The hub for Habit-Building Adventure
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, e.g. http://example.com

# Exclude these files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Include these plugins (if any)
plugins:
  - jekyll-feed
